### ISSUE TITLE
Wrong URL provided after booking confirmed

### ISSUE THREAD

**Issue by Milleus** [GovTechSG/butler-bot#15]
![image](https://user-images.githubusercontent.com/10268386/38009706-3bdc4a9e-3288-11e8-8397-fc29aa71905e.png)

wrong URL provided after booking confirmed. recommend to use constant for URL since it is in multiple messages.

**Comment by languantan** [comment]
yup its using constant, but the environment variable was wrong. please check again?

**Comment by languantan** [comment]
closing this issue as its server side issue
