### ISSUE TITLE
December Calendar

### ISSUE THREAD

**Issue by SimonGovTech** [GovTechSG/butler-bot#20]
Unable to book room for the month of November. Today is 31 Oct

**Comment by languantan** [comment]
closing this, fixed in [9f4b75](https://github.com/GovTechSG/butler-bot/commit/9f4b75611e241652c986dc0610e632f958fc6ec4)

**Comment by languantan** [comment]
closing this, fixed in [9f4b75](https://github.com/GovTechSG/butler-bot/commit/9f4b75611e241652c986dc0610e632f958fc6ec4)
